server:
  port: 8005
spring:
  application:
    name: zipkin-server
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
      config:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        file-extension: yml
management:
  metrics:
    web:
      server:
        auto-time-requests: false
